<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
    <BlazorCacheBootResources>false</BlazorCacheBootResources>
    <BlazorNoPrecompressIntegrityCheck>true</BlazorNoPrecompressIntegrityCheck>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    <PackageReference Include="blazor-dragdrop" Version="2.6.1" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.2.0" />
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.23" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.23" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.2" />
    <PackageReference Include="MudBlazor" Version="8.15.0" />
  </ItemGroup>

  <ItemGroup>
    <ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Auth\Components\" />
    <Folder Include="Features\Dashboard\Pages\" />
    <Folder Include="Features\Settings\Pages\" />
    <Folder Include="Infrastructure\Interceptors\" />
    <Folder Include="Infrastructure\Extensions\" />
    <Folder Include="Shared\Components\" />
    <Folder Include="wwwroot\audio\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\css\app.css" />
    <None Include="wwwroot\js\pets\petRenderer.js" />
    <None Include="wwwroot\js\auth.js" />
  </ItemGroup>
</Project>
